### ISSUE TITLE
リアクションデッキをサーバーと同期できるようにする

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#109]

**Comment by shiosyakeyakini-info** [comment]
できるらしい？って聞いたけどMisskeyのソース見る限り無理では？
fedibirdかなにかと勘違いしている可能性がある

**Comment by poppingmoon** [comment]
リアクションデッキはレジストリに保存されているので `i/registry/get` で取れるのですが、MiAuthとかで発行したトークンだと呼び出せなくてWebクライアントのトークンを使う必要があるみたいです

MilkteaではWebViewでログインしてもらってCookieからトークンを取っているようです

https://github.com/pantasystem/Milktea/blob/405d45524af73cc70875e36e0e3d1cf89bdd3ba6/modules/features/setting/src/main/java/net/pantasystem/milktea/setting/activities/ImportReactionFromWebViewActivity.kt#L143-L156

https://github.com/pantasystem/Milktea/blob/405d45524af73cc70875e36e0e3d1cf89bdd3ba6/modules/features/setting/src/main/java/net/pantasystem/milktea/setting/viewmodel/ImportReactionFromWebViewViewModel.kt#L73-L81

**Comment by pantasystem** [comment]
Misskeyは意図してid, pwでログインしたアカウントでないと
i/registry/get(レジストリ)からデータを取得できないようにしているみたいですね。
一時期レジストリをサードパーティ向けに開放するという話はあったのですが、
あくまでもWeb版とサードパーティでアクセスできる領域は分けるという話だったので、
Webクライアントとのレジストリの共有は主要開発陣の考えが変わらない限り厳しいと考えています。

**Comment by pantasystem** [comment]
当時のソースです。
https://misskey.io/notes/9a4jn7zl9d
https://misskey.io/notes/9a4jywxthu
https://misskey.io/notes/9a4jxxjkil
