### ISSUE TITLE
テキストを入力していないときにも投稿ボタンが押せてしまう

### ISSUE THREAD

**Issue by yuxxxx** [shiosyakeyakini-info/miria#120]
# 再現手順
1. 任意のタイムラインを表示
2. ✎ボタンを押す
3. **エラーが出る**

# 所感
エラーハンドリングはされているのでアプリが落ちることはないのですが、テキストが入力されてないときはボタンを無効化してそもそも押せなくしてあげたほうが親切かもしれません。

# 再現環境
端末: Pixel6
OS: Android 13
miria: 0.0.7+21

**Comment by shiosyakeyakini-info** [comment]
ノートの投稿画面：API呼び出し前にバリデーション
タイムラインの投稿欄：なにもしない

で修正しました

**Comment by shiosyakeyakini-info** [comment]
あ 待って
ノートの投稿画面の方のモーダル閉じ忘れた

**Comment by shiosyakeyakini-info** [comment]
閉じるようにしたのでクローズします
