### ISSUE TITLE
APIの型の差異を吸収する

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#124]
MisskeyそのものはNode.jsで動作するため、数値のものはECMAScriptの数値型で返される。
たとえば1e+100や-Infinityなどが返される可能性も理屈上は存在し、サーバー管理者がロールにこのような値を設定した場合アプリが受け付けなくなる。

**Comment by poppingmoon** [comment]
json_serializable 6.8.0でintの変換方法が変更されました
https://pub.dev/packages/json_serializable/changelog#680

この方法では一度numに変換してからtoIntでintにしているようです
toIntではintの範囲外の数は丸められるようなのでdoubleで表現できる1e+100や-Infinityが返されても問題は起こらなくなるはずです
https://api.dart.dev/stable/3.3.2/dart-core/num/toInt.html
