### ISSUE TITLE
リアクションしたユーザーを10人までしか見れない

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#125]
リアクションを長押しした際のダイアログでページネーションがないので10人目以降のユーザーを見ることができません

リノートのダイアログではPushableListViewが使われていて続きを見ることができるようになっています

**Comment by shiosyakeyakini-info** [comment]
untilIdで後続のリストをリクエストしてもエンドポイント側が返してこないからですね……
とはいえややこしいのでMisskey Webと同じように+28 のような表記にしていたほうがわかりやすい気はしてきました

**Comment by poppingmoon** [comment]
APIコンソールでちょっと試してみたのですが、offsetのほうは機能しているようです

ソースを見てもuntilIdは無視されていてoffsetは使われているようです

https://github.com/misskey-dev/misskey/blob/f5dfb64a528d705970d606d3f84ec9de2ef55d84/packages/backend/src/server/api/endpoints/notes/reactions.ts#L71-L79

**Comment by shiosyakeyakini-info** [comment]
わ ほんとだ（たまにある罠……
取れるなら取るような直しておこう
