### ISSUE TITLE
ノート検索画面でユーザーやチャンネルが選択できない

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#129]
ノート検索画面のユーザーやチャンネルを指定するボタンを押すと、ダイアログが表示されずに下記のエラーが発生します

https://github.com/shiosyakeyakini-info/miria/blob/baab03b5d39f1857169a54fac16cf70fc5242631/lib/view/common/account_scope.dart#L17

**Comment by shiosyakeyakini-info** [comment]
あ　これはまずい
（というか全般デグレが増えてきてるのでちょっと対策をしよう）
