### ISSUE TITLE
ときおりノートを二重に取得することがある

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#13]
WebSocketを重複して購読することがあり、ノートが二重や三重で表示されることがある

再起動すると治る

**Comment by shiosyakeyakini-info** [comment]
改善したので様子見　これで1週間程度発生しないならクローズ

**Comment by poppingmoon** [comment]
タブを高速で切り替え続けると再現しました

**Comment by shiosyakeyakini-info** [comment]
いま頻繁に再現してるけど直すのどうするのがいいんだろってなってる

**Comment by shiosyakeyakini-info** [comment]
とりあえずは1アカウント1個のWebSocketのコネクションにまとめたいけど……うーん

**Comment by poppingmoon** [comment]
dispose したときに disconnect が呼ばれてるんだけど await されてないからかコールバックが生きていて newerNotes にノートがどんどん追加されているみたいなのは見えてました

多分 StatefulWidget をやめて riverpod を頑張る？とか、場当たり的には newerNotes で重複したノートが追加できないようにするとかがいいのかなと思います

**Comment by shiosyakeyakini-info** [comment]
今後のことを考えるとriverpodでがんばるのが無難かなあ…… 

とりあえずでTimelineRepositoryでdistinctとかはたしかにできるけど、バッテリーの消費とかのパフォーマンスの問題を誤魔化してしまうのでちゃんと解決しておきたい

（というかmain streamも怪しい）

**Comment by shiosyakeyakini-info** [comment]
disconnectしたIDを持つようにして、そのIDが来たらもう一回閉じる とか……？ならできる気がしてきた
