### ISSUE TITLE
Android: apkをインストールする際に更新に失敗する

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#145]
apkからインストールしようとすると、端末に以前のバージョンがあるとき

> パッケージが既存のパッケージと競合するため、アプリをインストールできませんでした。

と表示されて更新に失敗します

このエラーが表示されてもインストール済みのmiriaをアンインストールしてからインストールすると正常にインストールされますが、タブ設定などの設定は捨てられてしまいます

0.0.8+31 までは同じ鍵で署名されていたのが [v0.0.9+35](https://github.com/shiosyakeyakini-info/miria/releases/tag/v0.0.9%2B35) 以降は毎回異なる鍵で署名されるようになったのが原因かもしれません

**Comment by shiosyakeyakini-info** [comment]
あーなるほど 自動的にデバッグビルドの署名になっててローカルで署名されてたけど、GitHub Actionsでビルドするようになって環境変わったから、署名が変わっちゃったのか
いずれにしてもストアに上げるときに証明鍵作らないといけないから、先やってしまおう

**Comment by poppingmoon** [comment]
[v0.0.9+37](https://github.com/shiosyakeyakini-info/miria/releases/tag/v0.0.9%2B37) のapkをインストールしようとするとエラーが発生します

adbからインストールしようとすると以下のエラーが発生しました

```
adb: failed to install app-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1225812480.tmp/base.apk: Attempt to get length of null array]
```

apkを展開して META-INF 以下を見ると, CERT.RSA, CERT.SF, MANIFEST.MF が存在しないことがわかります

**Comment by poppingmoon** [comment]
https://github.com/poppingmoon/miria/tree/build-apk
https://github.com/poppingmoon/miria/actions/workflows/deploy.yml

いろいろ試しているんですがうまくいっていません

**Comment by shiosyakeyakini-info** [comment]
BlueStacks App Playでもパッケージが破損しているって出てきた　とりあえず手元で再現できるようになった

**Comment by poppingmoon** [comment]
https://github.com/shiosyakeyakini-info/miria/blob/257dc903f3f5074bee7f24f59ee558f1aecd5d0a/.github/workflows/deploy.yml#L94

ここが間違っているみたいです

https://github.com/poppingmoon/miria/commit/d199a14a01181a23ce75d72005ccf3393bbe5f81
https://github.com/poppingmoon/miria/actions/runs/5383482872

**Comment by shiosyakeyakini-info** [comment]
あ　あれ？そこ？　なんかローカルでも普通にリリースビルド通らなくなっちゃった…

**Comment by shiosyakeyakini-info** [comment]
keystoreのパスワードからハイフン消したの作り直したらいけた

あーーーーーーーーー Organizationとかにコンマ入ってたらだめとかは知ってたけどパスワードにハイフンもだめなんだ

**Comment by poppingmoon** [comment]
[v0.0.9+38](https://github.com/shiosyakeyakini-info/miria/releases/tag/v0.0.9%2B38) がインストールできることを確認しました
ありがとうございます
