### ISSUE TITLE
設定をエクスポート/インポートできるようにする

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#146]
アカウント情報やタブ設定などの設定をjsonファイルか何かにエクスポートできるようにしておけば複数の端末での設定の共有などに便利だと思います

**Comment by shiosyakeyakini-info** [comment]
ドライブにJSONファイルとか置いて起動時に同期するところまでかんがえてる（そうすればAndroidとiPhone、ビルドすればMacとかWindowsとかの間とかでも同じ設定、同じリアクションデッキで動くし）

ただ複数アカウントのどれを見に行くかとかで悩んでる

**Comment by shiosyakeyakini-info** [comment]
マージしたのでクローズ
