### ISSUE TITLE
初回起動時にHTL, LTLの上にエラーが表示される

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#162]
初めてログインしたとき AccountRepository の accountDataValidated が空なのに以下の操作をしているため

https://github.com/shiosyakeyakini-info/miria/blob/de704be50e7b521c5b48487e3edcab8f9d8ccfc3/lib/repository/account_repository.dart#L61

2回目の起動時以降は load() が呼ばれるためエラーは発生しない

![](https://camo.githubusercontent.com/6200b50d227760ad6c94352d8fd4f30777e6a06ea6cf8f7b2db94b2f5a615c7b/68747470733a2f2f73332e61726b6a702e6e65742f6d6973736b65792f34356235323432362d393737652d346564372d613836362d6639633030646637333937312e706e67)

**Comment by shiosyakeyakini-info** [comment]
なおった
