### ISSUE TITLE
TL最下部にCW付きノートがあると、TL追加読み込みのボタンが隠れて押せないことがある

### ISSUE THREAD

**Issue by ndch3** [shiosyakeyakini-info/miria#163]
TL最下部にCW付きノートがある際に、当該ノートの「続きを読む」を押してノートを展開すると、TL追加読み込みのボタン(∨)が隠れて押せなくなることがあります。
Android版 0.0.9+45で確認。
同状況の再現が難しいためiOS版では未検証です。

**Comment by poppingmoon** [comment]
CWをつけることが義務付けられているチャンネルをタブに追加することで再現できました
続きを見るを押すとノートが展開されるのですが、それ以上スクロールすることができずにノートの途中までが表示された状態になります
これは最後のノートだけでなく、それより上のノートであっても展開後に画面をはみ出るなら同じことが起こります
PushableListViewではこのような挙動は見られませんでした

#180, #209 を実装する際に影響があると思います

**Comment by poppingmoon** [comment]
その場しのぎとしては、設定→全般設定→一覧の自動更新 を「自動で次を読み込む」にすることでこの問題は起こらなくなります

**Comment by shiosyakeyakini-info** [comment]
たしかに再現した
再現はしたけどこれどうやって直そう…

**Comment by shiosyakeyakini-info** [comment]
negativeChildrenDelegateとかpositiveChildrenDelegateが隠すボタン押したときとかに呼ばれないから、スクロールの最後尾が隠す前の状態から変わらないまんまみたいなことになってるのか

**Comment by poppingmoon** [comment]
全然わかっていないんですが、InfiniteListViewをやめて普通のListViewにするのって難しそうですか？

**Comment by shiosyakeyakini-info** [comment]
上方向や下方向に新たに取得しても、最上部にいないときはスクロール位置にとどめる必要があって、標準のListViewだとそれがうまくいかなかった（単純にリストをくっつけるとreversed: falseだと上方向の更新時に下に行ったりする）

いまの方法がいいとも言えないけど、カスタム絵文字の遅延読み込みとかで高さがころころかわるリストをそれなりに妥協してこうなってる

ほんとうはきれいに上下方向にリストを追加してもうまいこと表示できるリストのパッケージとかがあればよかったけど、どうも探しても見つからなかった
