### ISSUE TITLE
ノート詳細ページでスレッドの表示順が混ざっている

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#170]
notes/conversation が新しいノートが先頭になる順番でノートを返すため、リプライの連続の中間のノートを見ると

- 表示しているノートのリプライ先
- ...
- 最初のノート
- 表示しているノート
- 表示しているノートに対するリプライ
- ...
- 最新のノート

という順番で表示されています

表示しているノートの前後で逆の並び順に変わっているため分かりにくくなっています

**Comment by shiosyakeyakini-info** [comment]
ローカルではもうなおしてたけどコミットしてなかったやつ

**Comment by shiosyakeyakini-info** [comment]
なおったとおもうのでクローズしておきます
