### ISSUE TITLE
長いノートをおりたためるようにする

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#180]
長いノートが折りたたまれる条件

- `$[x2`, `$[x3`, `$[x4`, `$[scale`, `$[position`のいずれかが含まれていること, 9行以上の改行、500文字以上のテキスト、5枚以上の画像、4つ以上のURL のどれかを満たすこと
- `$[scale` `$[position` は個人的に折りたたまれる条件として微妙だと思ってる（実際折りたたまれないようにしてあるサーバーがある）

https://github.com/misskey-dev/misskey/blob/9fc3e19582a8ff6f60e6a0bc9d58b5ef11c1c7cd/packages/frontend/src/components/MkNote.vue#L207-L217

**Comment by shiosyakeyakini-info** [comment]
https://github.com/misskey-dev/misskey/blob/9fc3e19582a8ff6f60e6a0bc9d58b5ef11c1c7cd/packages/frontend/src/components/MkNote.vue#L207-L217

**Comment by poppingmoon** [comment]
TextPainterとかで描画されるサイズを取ってこれたら本当に長いノートだけを隠せそう

**Comment by shiosyakeyakini-info** [comment]
OverflowBox&ConstrainedBox, SizedBox, ClipRect, FittedBoxとかいろいろ試したけどどれを使ってもレイアウトが壊れる

**Comment by shiosyakeyakini-info** [comment]
Misskey Webの仕様を忘れて、同じMFMノード配下のテキストの文字数が一定以上の場合は省略表示にするとかにしないと無理かも

**Comment by shiosyakeyakini-info** [comment]
マージしたけどノートの詳細画面は省略する必要ないや…　なおす

**Comment by shiosyakeyakini-info** [comment]
続きを表示で画面更新して全体が更新されたのかまた続きを表示になることがある……
