### ISSUE TITLE
Mi Botanical Darkっぽいの の文字色がおかしい

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#186]
Mi Botanical Darkっぽいの の foreground と Mi Botanical Dark の fg の色が異なっています

https://github.com/shiosyakeyakini-info/miria/blob/4100ebfef62ea455b90ae4471373942d68d9ad76/lib/view/themes/built_in_color_themes.dart#L185

https://github.com/misskey-dev/misskey/blob/c9b9db13c7203f8065e232a10a4635619d8de72a/packages/frontend/src/themes/d-botanical.json5#L12

**Comment by shiosyakeyakini-info** [comment]
できればjson5ファイルから自動生成できるようにしたい、そうすれば他のテーマの解釈もできるようになる
（これChromeの開発者ツールみながら手で入れていったので……）

**Comment by poppingmoon** [comment]
assets_builderがわからないのですが、あれはどうやって動くのですか？
ユーザー定義のテーマをインポートできるようにするならdartで書くことになると思うのですが

**Comment by shiosyakeyakini-info** [comment]
ただたんにmisskeyのソースからassetsに固定のファイルを放り込む目的で作った（Misskeyのバージョンアップでカスタム絵文字の部分動いていないけど……）

misskeyのソースから固定のファイルを取り込んでassetsにjsonとかにして保存するだけなら言語はなんでもいい（多分最初作ろうとしたときはそのつもりだった）けど、インポートまでやろうとするとたしかにdartになる…
