### ISSUE TITLE
特定のサーバーのカスタム絵文字が表示できない

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#201]
下記 ( `:ifilter_misetehoshii@misskey.secinet.jp:` )

https://misskey.secinet.jp/proxy/image.webp?url=https%3A%2F%2Fmkd.secinet.jp%2Fmisskey-data%2Fd%2F1451d65d-46ee-430f-948b-58210a40208e.webp&emoji=1

もしかしてにじみすと一緒の原因かも？

**Comment by shiosyakeyakini-info** [comment]
ねむすぎーとぼすきーが対象かも （もしかしてもっとある？）

**Comment by shiosyakeyakini-info** [comment]
これにちゃんと対応できてない
https://github.com/misskey-dev/media-proxy/blob/master/SPECIFICATION.md

**Comment by shiosyakeyakini-info** [comment]
他のサーバーからぼすきーとのべるすきーのカスタム絵文字が見えないのはたぶん単純にカスタム絵文字が送られてないっぽい？
にじみす、ねむすぎー、BackspaceKeyの3サーバーで起きていて、いずれもメディアプロキシを介すとカスタム絵文字が表示できるようになった

**Comment by poppingmoon** [comment]
ぼすきーの :miriaru_face_bygamma: とかは localOnly ですね

**Comment by shiosyakeyakini-info** [comment]
名前やbio欄についてるカスタム絵文字もlocalOnlyだと見えないのか……
リモートで表示できるようにしてるし、Misskey Webでも実際見えないからもうそれはそういうものとするしかなさそう

（わざわざそのためにnodeinfoからsoftware.name判別してMisskeyだったらemojis取りに行ってそこからURL表示取得するとかやる意味もあんまりない気がする）

**Comment by shiosyakeyakini-info** [comment]
BackspaceKeyでこれが起きたのは、

1. カスタム絵文字をたくさん申請した人がアカウント消した
2. ドライブからかなりの数のカスタム絵文字が消失
3. Miriaは直接ドライブのカスタム絵文字を参照するため、そのまま消えたように見える
  - Misskey Webではメディアプロキシを介すため、メディアプロキシの画像をサーバー側でキャッシュしてる限りはまだカスタム絵文字の画像があるようにみえる

ということらしい

**Comment by shiosyakeyakini-info** [comment]
ねむすぎーの:ifilter_misetehoshii:も同じ状況のように見える（ドライブから消えてるが、それなりに使われてるのでメディアプロキシ経由のキャッシュは生きてる）
