### ISSUE TITLE
メディアタイムライン対応

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#205]
ノベルスキー、misskey.design、にじみすなどのサーバーに実装されている、メディアつきノートのみが流れるタイムラインを追加する

misskey.ioにも追加されるみたいです
`https://github.com/MisskeyIO/misskey/pull/103`

アンテナとチャンネル以外のタイムラインのapiは `withFiles` フィールドがあるのでメディアタイムライン非対応のサーバーであってもメディア付きノートを遡ることができます
ストリーミングについてはioの実装が逆輸入されれば HTL, LTL, STL, GTL に `withFiles` フィールドが追加されるため変更は小さくなると思います
それ以外のタイムラインや非対応のサーバーについてはリノート非表示と同じ方法で（クライアント側で）非表示にすることで、新しい種類のタブを追加することなく、どのタブでもメディアのみにすることができそうです

**Comment by poppingmoon** [comment]
できました

https://github.com/poppingmoon/miria/compare/2d56b8a...next-media-timeline

#279 がマージされたらPRします

**Comment by shiosyakeyakini-info** [comment]
メディアタイムラインをいれる前に公式が「ファイル付きのみ」を実装してしまったのでそっちを実装しようと思います…

**Comment by poppingmoon** [comment]
バックエンドは変わっていないように見えます
