### ISSUE TITLE
リアクションの表示数を制限できるようにする

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#209]
現在はノートについているリアクションはすべて表示されているが、特に長いリアクションが多くついているノートは縦長になる
タイムライン上のノートについてリアクションの一部のみを表示するようにすることで、一つのノートが占める領域を小さくして一画面で見ることができるノートの数を増やすことができる

- 条件をどうするか
  - リアクションの絶対数
    - 実装が簡単
    - 横長のリアクションが多いと同じ個数でも高さが大きくなる
  - 行数
    - リアクションの大きさによらず同じ高さに制限できる
    - 面倒そう
- 「もっと！」みたいなボタンをつけるか
  - 押したときの挙動は？
    - ダイアログを表示
      - Misskey Web はこれ
    - その場で展開
    - ノート詳細画面に飛ばす

**Comment by shiosyakeyakini-info** [comment]
…　みたいなのを出して、押したら展開がシンプルな気がする

**Comment by shiosyakeyakini-info** [comment]
16個（Misskey Webとおなじ）にするようにした

**Comment by poppingmoon** [comment]
多分時系列順で制限されていると思います
