### ISSUE TITLE
フォロー解除などを行う際にダイアログを表示する

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#211]
誤操作を防ぐため

Misskey Web では以下の操作に対して確認ダイアログが表示される

- フォロー解除
- フォロワー解除
- ブロック

**Comment by poppingmoon** [comment]
フォロワー解除 (following/invalidate) はmiriaには未実装でした

**Comment by shiosyakeyakini-info** [comment]
フォロワー解除はそれを実装するときにやるとして、あわせてリアクション取り消しも確認するようにした

**Comment by poppingmoon** [comment]
個人的にはリアクションを付けるときも確認してほしいけど、反射的にリアクションを付けるのが好きな人にとっては不便になりそう

**Comment by shiosyakeyakini-info** [comment]
（私自身が1日に2〜300くらいのリアクションを反射的に送るのでちょっといやかも）
