### ISSUE TITLE
Wikiを作る

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#221]
すべての機能に対して網羅的な解説をすることはこれから機能追加や変更があることを考えると難しいですが、現在misskey上で繰り返されている一問一答をまとめたページを作ることは可能だと思います
本来このような役割を果たすべき https://shiosyakeyakini.info/miria_web は製作者の多忙が原因で更新が滞っているようですが、複数人で編集ができるwikiに情報を集めることで負担が少なく実現できると思います

試しに自分のフォークで作ってみましたが普通にmarkdownで書けばいいだけなので簡単でした
https://github.com/poppingmoon/miria/wiki/FAQ

wikiの編集はgithubのアカウントを持っていないとできませんが、それでも本体に対するPRよりは敷居が低いと思うので新しいコントリビューターが増える入り口としても機能するのではないかと期待します

**Comment by poppingmoon** [comment]
わかりにくかったので追記しますが、このissueでの提案はこのリポジトリ (https://github.com/shiosyakeyakini-info/miria) にwikiを作成することです

**Comment by shiosyakeyakini-info** [comment]
作成してみました

**Comment by poppingmoon** [comment]
編集権限がなさそうです

**Comment by poppingmoon** [comment]
https://docs.github.com/ja/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by shiosyakeyakini-info** [comment]
ありがとうございます…！（使ったことがないのでめっちゃ探してた）

**Comment by poppingmoon** [comment]
編集できました
ありがとうございます
