### ISSUE TITLE
チャンネル情報がパースエラーになるものがある

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#233]
ログイン情報をつかわないでチャンネルを読み込むと、JSONのパースエラーになる

**Comment by poppingmoon** [comment]
これは修正されたからクローズされたのですか？

https://github.com/shiosyakeyakini-info/misskey_dart/pull/10 がこれを修正するPRだったので、必要がなくなったのであればこのPRもクローズしてください

**Comment by shiosyakeyakini-info** [comment]
ごめんなさい、単に重複してることに気がついたからクローズしました
