### ISSUE TITLE
i/notificationsを呼ぶ回数を減らす

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#253]
現在はタブの再接続をするたびにi/notificationsを呼び出しているが、streamingのmainを使ったり、通知をアカウントごとに管理することでこの回数を減らすことができる

i/notificationsは他のエンドポイントに比べてレートリミットが厳しく設定されているためRATE_LIMIT_EXCEEDEDを出しやすい

**Comment by shiosyakeyakini-info** [comment]
未読の通知あるかどうかは`api/i`使うようにしよ
