### ISSUE TITLE
ioの高負荷表示を回避する

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#312]
現在、各種タイムラインの読み込み時に `limit: 30` で過去のノートを取得しているが、misskey.ioではこのとき高負荷であればダミーのノートが30個表示されることがある
これは利用を阻害するものであるため、無効化したい

## `limit`を小さくする

初回読み込み時に `limit: 1` とすることで、ダミーを表示する数を1つまで減らすことができる
ただし、過去のノートを表示するために次回の読み込みを待たなければならない

## タイムラインでidの重複を許さない

~~ダミーノートはすべて同じidを持つため、ダミーを表示する数を1つまで減らすことができる
`limit` を小さくしたときと同じデメリットがある~~
連番だったのでこの方法は使えない

## `untilId` に十分大きなidを指定する

初回読み込み時の `untilId` に `null` の代わりに `"ZZZZZZZZZZ"` のような十分大きな値を指定することで、`untilId` が `null` のときと同様の結果を得ながらダミーが返ってこないようにすることができる

**Comment by shiosyakeyakini-info** [comment]
（ioの方針だと思ってるので、あんまりへたに何かせずに素直にそのままにしておくほうがよさそうって思う）

**Comment by poppingmoon** [comment]
limitが大きく設定されていることでダミーが表示される量がMisskey Webに比べて大きくなっていることが問題だと思っています

理由があってlimitを大きくしているのであれば、それに伴ってダミーが多くなりすぎることにも対応するべきだと思います
ioの方針に従うのであれば、limitもMisskey Webと同じ10に下げるべきだと思います

**Comment by poppingmoon** [comment]
ホーム、アンテナ、リストタイムラインのlimitが30でした

アンテナとリストに関してはホームタイムラインを見て全部30だと勘違いしてコピペしたのだったと思います
