### ISSUE TITLE
リロードボタンを連打すると新しく受信したノートが増殖する

### ISSUE THREAD

**Issue by Kur0den** [shiosyakeyakini-info/miria#335]
Galaxy S10
Android 12
Miria 1.0.2+58で発生

このバグを発生させてから通知欄を開くと429エラーが表示される

**Comment by Kur0den** [comment]
スクリーンショット

![Screenshot_20230921-131658.png](https://github.com/shiosyakeyakini-info/miria/assets/69957747/740cee01-2295-4e89-bfe2-517416ba2ceb)

![Screenshot_20230921-131702.png](https://github.com/shiosyakeyakini-info/miria/assets/69957747/b142f704-4193-4413-a6a6-2e6cd1855621)

**Comment by shiosyakeyakini-info** [comment]
1.0.3+64でリロード処理だいぶなおしたのでもう起きないかも
