### ISSUE TITLE
リアクションが繰り返し表示される

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#337]
環境
- Android
- v1.0.3+62
- BackspaceKey 2023.9.0-rc.2-bsk-1.1

リアクション一覧を表示しようとすると同じ内容が繰り返し表示され続ける。

参考: https://misskey.backspace.fm/notes/9k0cjqrrhf

**Comment by poppingmoon** [comment]
notes/reactionsはoffsetが無くなってuntilIdのみになったようです

https://github.com/misskey-dev/misskey/commit/cac1c2f1e9b1f6121935ac74f6f0ea1410c97e64

以前のバージョンではuntilIdが機能していなかったので(#125) 、この変更に対応すると古いバージョンのサーバーでは正しく表示されなくなります
これを防ぐためにはサーバーのバージョンによってapiの呼び出しを変える必要があります

**Comment by shiosyakeyakini-info** [comment]
お知らせはoffsetとuntilId両方つけてリクエストするようにしたので、こっちも同じようにするしかなさそう
