### ISSUE TITLE
TL画面上で表示されるお知らせがテキストを表示しきれていない

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#368]
TLの画面上部に表示されるお知らせのテキストが、折返しがおこなわれていない（か、適切でない）ため、全体を見ることができない。
既読を押すにはお知らせページを開く必要があるため、読めなくて困ることは少ないとは思うものの、文章全体が表示されないことへの違和感は大きい。
![Screenshot from 2023-10-01 20-17-11](https://github.com/shiosyakeyakini-info/miria/assets/66727014/325f3670-c8d6-4e0a-a40d-fd41773a437e)

**Comment by shiosyakeyakini-info** [comment]
Misskey Webも1行分しか表示してないので、複数行をそもそもやめてellipsisかけるのがよさそう
