### ISSUE TITLE
リアクションしたアカウント一覧の内容がループしている

### ISSUE THREAD

**Issue by mik-claire** [shiosyakeyakini-info/miria#371]
misskey.ioでは発生せず、確認した環境はbuicha.social（Misskey 2023.9.3）のみ。
ノートに付けられたリアクションをロングタップするとリアクションしたアカウント一覧が開くが、
同じアカウントが無限に繰り返し表示される。
スクリーンショットでは1アカウントのみリアクションしたものを表示しているが、
例えば3アカウントが同じリアクションしていた場合はその3アカウントが同じ並び順で繰り返し表示される。
（こちらと同事象？→ https://github.com/shiosyakeyakini-info/miria/issues/325 ）

![IMG_1554](https://github.com/shiosyakeyakini-info/miria/assets/15326729/a057fcea-b759-445b-9783-9f0d83822c4a)

**Comment by shiosyakeyakini-info** [comment]
#337 で修正済みで、修正したバージョンがすでにAndroidとiOSの両方でストアにあがっていると思います…！

**Comment by mik-claire** [comment]
AppStoreから直接検索して更新しました、無事修正されていることを確認できました！
お手数かけしました、ありがとうございます！
