### ISSUE TITLE
上から下へのスワイプでタイムラインの更新ができると嬉しい

### ISSUE THREAD

**Issue by mik-claire** [shiosyakeyakini-info/miria#372]
（あくまで要望ですのでお暇なときにでも…）
公式Xと同じような動作の更新処理ができたら使いやすいなあと思って。
今だとどうしても画面右上まで指を持っていかないといけなくて…

**Comment by poppingmoon** [comment]
#279 に含まれています

**Comment by mik-claire** [comment]
ありがとうございます！重複になってしまいますので、こちらのissueはクローズしますね。
