### ISSUE TITLE
jpegで画像をアップロードする際、EXIFを削除する

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#375]
なんかioだとエラーになるらしい

**Comment by poppingmoon** [comment]
Pixel 5aで撮影した写真をioにアップロードできることを確認しました
また、同じ写真がMisskey Webで「オリジナル画像を保持」にチェックを入れている場合アップロードできないことを確認しました

元画像(zip)
https://media.misskeyusercontent.com/io/ecea38a4-b4e8-4f5e-86fe-b26acd298aa2

アップロード後
https://media.misskeyusercontent.com/io/77a1f520-7f17-4039-b6c4-f75a90a363f2.jpg

**Comment by shiosyakeyakini-info** [comment]
Pixelでの動作確認たすかります（持ってなかったので）！
ありがとうございます！！！
