### ISSUE TITLE
Google Fontsを使えるようにする

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#420]
Google Fontsで公開されているフォントを適用できるようにする

pubspec.yamlには既に入っていた

https://github.com/shiosyakeyakini-info/miria/blob/bfe996f959757274b90598f5e492f1e2bb7c4c1f/pubspec.yaml#L37

**Comment by poppingmoon** [comment]
https://github.com/poppingmoon/miria/commit/96f948fb96180e32378fd36101684e5910355c05

フォントを切り替えるのはできたけど大量にフォントが表示されてわかりにくい

![image](https://github.com/shiosyakeyakini-info/miria/assets/63451158/e3525576-83d5-4691-ab90-eb0380ae94ce)

**Comment by Npepperlinux** [comment]
全フォントファミリーの数が1576種類あることを考えると、[`flutter_font_picker`](https://github.com/whiplashoo/flutter_font_picker)を利用するか、選択するフォントを日本語（`草薙、薔薇`が表示可能）に対応したもの（48種類）に絞り込む必要があると思います（前者を選んでも`You should only use a limited number of them for performance and data saving`となっていますが…）。

<details>
<summary>日本語フォント（漢字可）一覧</summary>

```
"Noto Sans Japanese",
"Noto Serif Japanese",
"M PLUS Rounded 1c",
"M PLUS 1p",
"Dela Gothic One",
"Zen Kaku Gothic New",
"Kosugi Maru",
"Shippori Mincho",
"Zen Maru Gothic",
"BIZ UDPGothic",
"Zen Antique",
"Kosugi",
"Kiwi Maru",
"Zen Old Mincho",
"M PLUS 1",
"Shippori Mincho B1",
"Klee One",
"RocknRoll One",
"Zen Kaku Gothic Antique",
"Kaisei Decol",
"Zen Kurenaido",
"M PLUS 2",
"DotGothic16",
"Yusei Magic",
"Kaisei Opti",
"BIZ UDPMincho",
"Reggae One",
"Kaisei Tokumin",
"PottaOne",
"Rampart One",
"Shippori Antique",
"Stick",
"BIZ UDGothic",
"Hani Mincho",
"Hachi Maru Pop",
"IBM Plex Sans JP",
"Mochiy Pop P One",
"Yuji Mai",
"Yuji Syuku",
"Yomogi",
"Zen Antique Soft",
"Kaisei HarunoUmi",
"New Tegomin",
"Shippori Antique B1",
"BIZ UDMincho",
"M PLUS 1 Code",
"Yuji Boku",
```

ひとつ見落としているかもしれない。

</details>

**Comment by poppingmoon** [comment]
https://github.com/poppingmoon/miria/commit/351ad2d8a8fddb0883b9ccd4c30626a3e1c62a84

flutter_font_picker を使ってみました

![image](https://github.com/shiosyakeyakini-info/miria/assets/63451158/fc0e434d-44d9-47a4-83c1-b8bb61156c60)

どうせたまにしか使わない機能だろうということでREADMEを無視しています

**Comment by shiosyakeyakini-info** [comment]
[Google Fontsの日本語の枠](https://fonts.google.com/?subset=japanese&noto.script=Hira) にあるフォントを選べる、`$[font.`毎(monospace, serif, cursive, fantasy)に選べる　でやってみよ

**Comment by poppingmoon** [comment]
2154698e9dedc197e33e52b213d54de1dfa12673 で実装されたためcloseします
