### ISSUE TITLE
Flutter 3.16.0に対応する

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#440]
2023年11月16日にFlutterのstableチャンネルのバージョンが3.16.0に上がったが、これによってテストが落ちるようになった

https://github.com/shiosyakeyakini-info/miria/actions/runs/6897725061/job/18766425418#step:7:169
https://github.com/shiosyakeyakini-info/miria/actions/runs/6897725061/job/18766425418#step:7:225
https://github.com/shiosyakeyakini-info/miria/actions/runs/6897725061/job/18766425418#step:7:251

Flutter 3.16.0 では useMaterial3がデフォルトでtrueになり、textScaleFactorとWillPopScopeがdeprecateされている

https://docs.flutter.dev/release/breaking-changes#released-in-flutter-316

**Comment by shiosyakeyakini-info** [comment]
いったんこれはクローズしてMaterial3にするのを別のIssueにしようと思います
