### ISSUE TITLE
GitHub Actions Marketplace Workflowにdeprecatedなものがあり、テスト時にアラートが出ている

### ISSUE THREAD

**Issue by bateleurX** [shiosyakeyakini-info/miria#456]
# どういうこと？
現在miriaのリポジトリのgithub actionsに設定されているmarketplace workflowのうち、node12で書かれているものが含まれています。
node12はすでにgithub actions実行環境から削除されており、今はnode16を使って動かされています。そのため意図通りに動かない可能性があります。このことはaction実行時のwarningで出力されています。

# どのような対処？
いずれもworkflowを更新し、node20 or node16で書かれたactionに更新した方がよいでしょう。
このあとで更新するPRを作成いたしますので、一度ご確認いただければと思います。

# warningの例
https://github.com/shiosyakeyakini-info/miria/actions/runs/6923308541
![image](https://github.com/shiosyakeyakini-info/miria/assets/2516276/86ae9d75-88ed-474d-809c-e2a2569ebde5)

**Comment by poppingmoon** [comment]
deprecatedなのはcheckoutだけじゃないからfixedではないと思う

**Comment by shiosyakeyakini-info** [comment]
あれま
