### ISSUE TITLE
「リノート直後のノート」ページで末端がなくなる

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#479]
タイトルのとおり。
リノート直後のノートが存在しなければ発生しない（ように見える）。

https://github.com/shiosyakeyakini-info/miria/assets/66727014/73b3c383-05d3-4ea9-81c3-95bbd64e3b59

**Comment by poppingmoon** [comment]
これも #478 と同じエラーが出ているのが原因です
