### ISSUE TITLE
ロールタイトルにカスタム絵文字が設定されていても表示されない

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#480]
「そもそもそこにカスタム絵文字設定できたんだ」

|Misskey Web|Miria|
|:-:|:-:|
|![screenshot_231211220232](https://github.com/shiosyakeyakini-info/miria/assets/66727014/5c6cd8cb-6479-447a-bb68-9956f1385079)|![screenshot_231211220155](https://github.com/shiosyakeyakini-info/miria/assets/66727014/4ea1ba6c-e1d2-4db6-9a13-207027965e16)|

**Comment by poppingmoon** [comment]
カスタム絵文字が設定されているわけではなく（できない）ロールのiconUrlの画像を表示していないだけみたいです
