### ISSUE TITLE
要望：コードブロックはmonospaceフォントで表示して欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [shiosyakeyakini-info/miria#489]
- OS：iOS 17 （iPhone SE3）

タイトル通りです。（ちょっとチャレンジしてみたい感が少しだけあります）

**Comment by Npepperlinux** [comment]
「設定」→「全般設定」の下の方にある「フォント（$[font.monospace やコードブロック 用）」からフォントを変更できると思います。

**Comment by sevenc-nanashi** [comment]
おっと、ごめんなさい…

デフォでそれっぽいフォントにするのは可能だったりしますか？

**Comment by poppingmoon** [comment]
monospaceのデフォルトのフォントは以下の部分で定義されています（iOSではMonaco）

https://github.com/shiosyakeyakini-info/miria/blob/6b01984009d45fdad24d5164ef9b35874fcb43c6/lib/view/themes/app_theme_scope.dart#L119-L141

@shiosyakeyakini-info fontFamilyFallbackが絵文字と同じものになっていますがこれは意図したものですか？
2154698e9dedc197e33e52b213d54de1dfa12673 で変更される前のコードブロックのフォントは以下のようになっていました

https://github.com/shiosyakeyakini-info/miria/blob/7fdccfdb4bf36ecd18a2db7aa8b339fec52b8dee/lib/view/common/misskey_notes/mfm_text.dart#L201-L206

**Comment by shiosyakeyakini-info** [comment]
OSごとに振り分けたからごちゃまぜでフォールバックする必要がなくなってそうしたはず

（iOSの場合はMonacoじゃなくてMenloにしてあげないといけない気がしてきた）

**Comment by poppingmoon** [comment]
絵文字のフォールバックとモノスペースのフォールバックが全く同じであることがおかしいのではないかと思います
例えばメイリオはモノスペースではありません

**Comment by shiosyakeyakini-info** [comment]
Consolasに含まれてないグリフのためにフォールバックしてるのでそれは仕様

**Comment by poppingmoon** [comment]
了解しました
MenloやNoto Monoをフォールバックに追加したほうがいいのではないかと思います
