### ISSUE TITLE
リアクションデッキが消失する

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#493]
## 現象

- Androidのみで発生 (iOS, Mac, Linuxで再現しない)
- `v1.0.13+87`では発生しない、`v1.0.13+91`で発生する
- この状態になると、リアクションデッキを保存してもタスクキル後、再度消失した状態になる

## 再現手順

そらいろさん環境

- エミュレータ(API30/Android 11)での検証
  - タグ`v1.0.12+84` `v1.0.13+88`でビルドしてデバッグ起動し、リアクションデッキを作成後、`v1.0.13+91`で再度ビルドしてデバッグ起動しても再現しない
  - 上記をProfileでビルドしても再現しない
- Galaxy A22 5G (Android 13)での検証
  - GitHub版のapkを`miria-1.0.12+84.apk` `miria-1.0.13+87.apk` `miria-1.0.13+88.apk` の3つでリアクションデッキを作成し、`miria-1.0.13+91.apk`をインストールしても再現しない

## 考察

- 他になにかの手順が必要の可能性がある
- 特定のメーカー、バージョンでしか発生しない可能性がある
- Debugビルド、Profileビルドでは発生せず、Releaseビルドでのみ発生する可能性が高い

**Comment by Npepperlinux** [comment]
現象が起きることはわかっているものの、問題が起きたときの設定ファイルを誤って削除してしまったため再現不能＆確認不能になってしまった。
# 確認環境
- SHARP Android One S3(Android 10)での検証
  - `1.0.9+79`で2つのアカウントを認証後、リアクションをそれぞれ2つ設定、GitHub版にあるAPKで`1.0.10+82`,`1.0.11+83`,`1.0.12+84`,`1.0.13+91`の順番にアップデートしたものの再現しなかった
## 確認したとき
- moto g7(Android 13 - LineageOS 20)
  - GitHub APK版をインストール、以降リリースごとにAPKをアップデートしていた
  - 4つのアカウントで認証していた
  - 問題発生後、`miria.json`をインポートすることで一時的にリアクションデッキが復旧するものの、再起動すると再び失われている
    - 使用した`miria.json`は、同じ頃にインストールしたLinux版のものを流用

**Comment by shiosyakeyakini-info** [comment]
Play Storeはあんまり関係なさそう

**Comment by natumi-kaoru** [comment]
SONY Xperia 10 II（RAM: 4 GB, Snapdragon 665; Android 12） でGoogle Playにある現行版を利用しておりますが、標記の事象が発生しました。
タスクキル後 再起動したとき、またタスクキルを行わずとも、アプリを再度フォアグラウンドにした際にメモリ不足等でアプリが再起動となったときに発生します（∴ ただ一度バックグラウンドにして、再起動を伴わずにフォアグラウンドに戻ったときには発生しません）。

**Comment by shiosyakeyakini-info** [comment]
まっさらの状態でインストールしてアップデートしても起きないということは、条件が不足してる

家帰ったらSharedPreferenceを使ってるところ全体で再現条件かんがえてみる

**Comment by kyoka-h** [comment]
当方 Samsung Galaxy S8(Android 9, RAM : 4GB) でGoogle Playにある最新版を適用したところ、当該事象が発生するようになりました。

**Comment by shiosyakeyakini-info** [comment]
SharedPreferenceを使ってるところは
- 各アカウントごとの設定
- 絵文字
- 全般設定
- タブ設定
- 通知の未読位置

の5箇所　でも、

1. v1.0.13+84でログイン
2. 通知の画面を開く、全般設定とタブの追加を行う
3. リアクションデッキを設定する
4. v1.0.13+91に上げる

の手順でも再現しなかった

**Comment by shiosyakeyakini-info** [comment]
もっと大昔のバージョンから使い続けてると起きるとか？

**Comment by shiosyakeyakini-info** [comment]
こまこまのこまり

**Comment by shiosyakeyakini-info** [comment]
5サーバーを紐づけてそれぞれにリアクションデッキを設定しても再現しなかった
数が問題というわけでもなさそう

**Comment by shiosyakeyakini-info** [comment]
ソースコード的に考えると、影響している可能性が高そうなのは 7db42ad と 1acbe9c
でアカウント設定 (AccountSettings) にフィールド追加したところ

JSONのパースとかでエラーになって設定情報が取れずにエラーになって、その結果空の（初期値の）インスタンスになってる可能性が高いとは思う　でも、それだとAndroidだけで起きる理由がまったくわからない（他の環境でも起きないとおかしい）

**Comment by 4ster1sk** [comment]
手持ちの4台の端末(sense/sense3/sense4/redmi 9T)で再現できたっぽいので手順を書いておきます。


1. リアクションデッキの設定(これは後でも先でもどちらでも)
2. 異なるサーバのユーザプロフィールを開らいて絵文字情報を保存させる(一応ノートタブにも切り替える) ※絵文字の多いサーバを推奨
3. 2の手順を繰り返す
4. 10～20程度行ってると、ユーザプロフィールとノートを切り替えする際に若干もっさりし出すのでそのぐらいになったらアプリを終了させる
5. 再度起動してデッキを確認すると消えてる

**Comment by shiosyakeyakini-info** [comment]
あーーーーーーーーーーーーーー

ログインしないサーバーも絵文字保存してしまってる あんたか

**Comment by 4ster1sk** [comment]
リリースビルドでは再現できたんですが、デバッグビルドで試してみたところ再現できなくなりました…。
ただ、デバッグビルドだとaccount_settingsにログインしていないサーバ（絵文字をキャッシュしたサーバ）の情報が増えていて謎なんですよねえ…。

**Comment by poppingmoon** [comment]
https://github.com/shiosyakeyakini-info/miria/issues/493#issuecomment-1867046757 の方法で再現しました

この現象が起こるとき、shared_preferenceからアカウント設定がロードされるよりも先に以下の行が実行されているようです

https://github.com/shiosyakeyakini-info/miria/blob/89f01aed67b6e2655c03e6d8e7f69ad06a9008a0/lib/view/common/main_stream.dart#L28

MainStreamRepositoryのconnectはconfirmNotificationを呼び、confirmNotificationはアカウント設定をshared_preferenceに書き込みます
そのため、アプリの起動時にアカウント設定が読み込まれるよりも前に書き込まれることになりリアクションデッキが消失することが起こっていると考えられます

SplashPageではアカウント設定をロードする前にAccountRepositoryのロードを行っています

https://github.com/shiosyakeyakini-info/miria/blob/89f01aed67b6e2655c03e6d8e7f69ad06a9008a0/lib/view/splash_page/splash_page.dart#L27-L30

今回の問題が起こった原因はこれらのロード時間が長くなったことで読み込みが書き込みに間に合わなくなったことだと思います
splash_page.dartの27行目と28行目の間に `await Future.delayed(const Duration(seconds: 1));` を挟むとwindowsのデバッグでも同様の現象が発生することを確認しました

対策として、MainStreamウィジェットを削除するべきだと思います
MainStreamはMaterialAppを囲んでいるウィジェットであり、SplashPageによる読み込みが終わっていることを保証できません
また、このウィジェットは全てのアカウントに対してmainStreamRepository.connectを呼ぶために存在しているようですが、これはタブが変更される際にも呼ばれるものなのでここで呼び出す必要はないように思います

**Comment by shiosyakeyakini-info** [comment]
- もともとmainだけ呼んでたのは通知とかカスタム絵文字の更新はそのタブを表示してなくても拾っておきたかったから
- 現象的にはアカウントを２０個とか追加しても起きそう（15個くらい紐付けてる人は過去に見た記憶がある）

みたいなところかんがえると、読み込み終わるのを待ってからつなぎに行くようにしたほうがよさそう

**Comment by poppingmoon** [comment]
タブを移動しないと通知は見られないですしカスタム絵文字の更新をタブが表示される前にする理由もないように思います

**Comment by shiosyakeyakini-info** [comment]
カスタム絵文字の更新はサーバーから送られてくる方（emojiUpdatedとか）
