### ISSUE TITLE
Misskey.ioだけTLの読み込みに非常に時間がかかるようになった

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#494]
~~Misskey.ioにきらわれてそう~~

もともと`api/i/notification`の呼び出しはunawaitedだったのに、今回の修正で`api/i`と`api/meta`がunawaitedにならなくなったため

**Comment by shiosyakeyakini-info** [comment]
なんか突然解決した　謎

**Comment by poppingmoon** [comment]
WebSocketの接続でタイムアウトしているみたいでした
startTimelineをapiでノートを取得した後で呼び出すようにすれば過去のノートは表示されるようになると思います
#279 をマージした自分のフォーク https://github.com/poppingmoon/miria では過去のノートは普通に表示されていました

**Comment by shiosyakeyakini-info** [comment]
Future.waitで並列にしたらマシになるかな
（単純に入れ替えるとTLの取得が重いときに困る）
