### ISSUE TITLE
AndroidにおけるEmojiCompat対応

### ISSUE THREAD

**Issue by tesmite** [shiosyakeyakini-info/miria#552]
Android版において現状では端末が対応している絵文字しか表示されず古いバージョンの端末では新しい絵文字は表示されません。
Twemojiを利用することによってそれらの端末でもTwemojiが対応している絵文字は表示されますがTwemoji自体の将来性の不安定さからか2024年2月10日時点の最新版(v1.0.16+100)においてもUnicode 15で追加された絵文字に対応できておらず、また入力欄においては端末デフォルトの絵文字が使用されていることで追加された絵文字の使い勝手があまり良くない状況です。
EmojiCompatに対応すれば古いバージョンの端末においてもGoogleによって自動的に絵文字が更新され、Google側で対応済みの絵文字はすぐに利用できるようになります。
また表示面でも端末が対応している絵文字と同じように表示されるのでユーザー側が意識すること無く新しい絵文字を利用できるかと思われます。
ただしEmojiCompatに対応するにあたってAppCompatを利用する必要があるようです。

**Comment by shiosyakeyakini-info** [comment]
FlutterでAndroidネイティブの絵文字を使う余地がほとんどないのでこれはやらないかも
