### ISSUE TITLE
実機でリリースビルドなのにShare Extensionだけデバッグ扱いされる（iOSのみ）

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#569]
実機でprofile/releaseビルドをしているのに、Share Extensionから起動するとデバッグ起動扱いされる

https://misskey.backspace.fm/notes/9r8w1uquyc

Configurations は下記のとおり、正しく設定しているはず

![スクリーンショット 2024-03-24 19 25 05](https://github.com/shiosyakeyakini-info/miria/assets/2309943/50f4e8cd-7dd7-45e8-b3f9-3e125664cfce)

**Comment by 4ster1sk** [comment]
flutter/bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframeworkの方を使うと良さそう？

**Comment by shiosyakeyakini-info** [comment]
> To build for release or profile modes, find the framework file under the ios-release or ios-profile folder, respectively.

https://docs.flutter.dev/platform-integration/ios/app-extensions

あーーーーーーーーーーーーーーーーー！

**Comment by shiosyakeyakini-info** [comment]
![スクリーンショット 2024-03-26 7 10 58](https://github.com/shiosyakeyakini-info/miria/assets/2309943/22aae3b5-314c-40cd-8bb5-36b5612c8be3)

ぐえー

**Comment by shiosyakeyakini-info** [comment]
ViewController作るときに一緒に作れないとかありそう　と思って`viewDidLoad()`で作っても同じエラー吐かれた
うーん……

**Comment by shiosyakeyakini-info** [comment]
あああああ実機でもちゃんと動いた

![image](https://github.com/shiosyakeyakini-info/miria/assets/2309943/add78d7f-905c-4605-b4e4-70e0f315f92d)

**Comment by shiosyakeyakini-info** [comment]
できたのでおわり
