### ISSUE TITLE
Miria v2

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [shiosyakeyakini-info/miria#572]
Miriaをごっそりリファクタリングする

- [x] Lintを強めに設定する 特に`unawaited_futures` `discarded_futures` とかを入れる
- [x] 単なるシンプルめのダイアログを表示するために`showDialog`を使わずに、ダイアログの状態管理をする`StateNotifier`を作ってその状態を受けて表示できるようにする (Misskey本家も割とそんな感じの動きしてる)
  - `async gap`の対策
  - `StateNotifier`の`Future`とかで一連の処理でユーザーのダイアログ操作待ちをさせたいときがある 画像つきノート投稿時のサーバーからのセンシティブ判定とか
  - 次いで、ダイアログをAdaptiveにする
- [ ] Material 3にする
- [x] 既存のProviderをcode generationに置き換える、状態をイミュータブルにする
- [x] fvmを使い、ビルド毎のFlutterのバージョンを固定する
- [x] ローカルの状態管理をflutter_hooksでやる
- [x] `showDialog` や `showModalBottomSheet` を auto_route で呼び出すようにする
- [x] AccountScopeをInheritedWidgetではなく、Scoped Providerにしてdependenciesに入れる 
- [x] Privacy Manifest対応
- [ ] 既存のプルリクエストの整理
- [ ] 命名規則がばらばらなのでなおす （語順で動詞を先にする）
- [ ] StateNotifierとPageを同じディレクトリ階層にしてわかりやすくする
- [ ] もしもこれの対応中にRiverpod 3.0の新機能がきたら、それは恩恵にあずかる
- [ ] LAN内のMisskeyサーバー（ポート指定、HTTP通信）でもログインできるように（デバッグ時）

**Comment by poppingmoon** [comment]
[require_trailing_commas](https://dart.dev/tools/linter-rules/require_trailing_commas) を入れてもらいたいです（インデントが揃うし差分が見やすくなる）

**Comment by shiosyakeyakini-info** [comment]
- APIの読み込みも全面的に見直す
    - discard_future, unawaited_futureのLintを入れて全部みなおす 
    - なにもしてない、ローディング中、完了時の状態を管理して、二重リノートすると画面が真っ白になるみたいなやつをなんとかする

**Comment by shiosyakeyakini-info** [comment]
負債が多すぎてなきそう

**Comment by poppingmoon** [comment]
AriaではAPIの呼び出しは基本的に全て `AsyncNotifier` を使って行っています

Notifierのbuildの中でasyncを書くとデータとローディングとエラーの3状態のsealed classみたいなやつを勝手に返してくれるので、switchでそれぞれのviewをまとめて書けます
ファイルは増えますがFutureとsetStateでいちいち状態をいじるよりは楽だと思うのでおすすめです

例: https://github.com/poppingmoon/aria/blob/a5e9da3f5f4567269a401f13dabbe68a2fbdd66d/lib/view/page/explore/explore_roles.dart#L22-L44

**Comment by shiosyakeyakini-info** [comment]
riverpodの2585でもにょってる ん～～～もうriverpod 3.0-dev.3にするか

**Comment by poppingmoon** [comment]
riverpod_generatorに移行するなら[riverpod_lint](https://pub.dev/packages/riverpod_lint)を入れてみてもいいかもしれません
たぶん今の状態で入れると[avoid_build_context_in_providers](https://pub.dev/packages/riverpod_lint#avoid_build_context_in_providers-riverpod_generator-only)が大量に出ると思います

**Comment by shiosyakeyakini-info** [comment]
riverpodのドキュメントを読み直してたらflutter_hooks使うと便利なのでは？ってなってきた
それもやっていこ

**Comment by shiosyakeyakini-info** [comment]
ぬぁーーー ChangeNotifierはriverpod_generatorでlistenされない そういう仕様らしい
むむ……
