### ISSUE TITLE
[beta] リロードボタンを連打すると新しく受信したノートが増殖する

### ISSUE THREAD

**Issue by Kur0den** [shiosyakeyakini-info/miria#623]
Galaxy S23
Android 14
Miria 2.0.0+103 で発生

#335 と似たような挙動をする

スクリーンショット
![バグ発生時のスクリーンショット](https://files.kur0den.net/chpk/ffb26df9-00a3-4709-a396-20d9f0fdc5d3.jpg)

**Comment by Kur0den** [comment]
リアクションも増殖してた

**Comment by shiosyakeyakini-info** [comment]
なおった
