### ISSUE TITLE
[beta] テーマが適用されていないポップアップが表示される

### ISSUE THREAD

**Issue by Kur0den** [shiosyakeyakini-info/miria#629]
投票の確認時に標準っぽい見た目のポップアップがでてくる
他の場所でも見た気がするけどわすれた

![ポップアップの画像](https://files.kur0den.net/chpk/a2d8772e-1624-4f09-80f2-410fbe8b5226.jpg)

**Comment by shiosyakeyakini-info** [comment]
アダプティブにしたので仕様かも

**Comment by poppingmoon** [comment]
これは修正するべきだと思います

スクリーンショットにあるようにDialogScopeが表示するダイアログがAndroidなどではMaterial 3のダイアログになっており、色はデフォルトの紫でダークテーマも反映されていません
これはDialogScopeがAppThemeScopeよりも外側にあることが原因で、この二つを入れ替えることで修正できます

https://github.com/shiosyakeyakini-info/miria/blob/4eb70b6b0fc2c41cd7376ce3a1e8758d23ba8550/lib/main.dart#L133-L142
