### ISSUE TITLE
[beta] 投票の選択肢の入力フォームにローマ字で入力ができない

### ISSUE THREAD

**Issue by Kur0den** [shiosyakeyakini-info/miria#630]
入力が即時確定されるような挙動をする

`にゃーん`と入力した際の結果
![image](https://github.com/user-attachments/assets/ac095d21-19d6-4484-9c37-0be78bdb5f77)

**Comment by shiosyakeyakini-info** [comment]
ローマ字入れられるようになったけどなんか削除がおかしくなった
