### ISSUE TITLE
リモートユーザーからのフォローメッセージでMFMが表示されない

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#650]
Miria 2.0.0+114
![Screenshot_20241106-124607_miria~2](https://github.com/user-attachments/assets/04211f9e-3b1a-4ed7-b7fe-ecc2df8ac995)

**Comment by 4ster1sk** [comment]
![Point Blur_20241106_200531.png](https://github.com/user-attachments/assets/c7fcad84-6683-47c5-82e3-c9aa75356317)

カスタム絵文字だけでいいかも
