### ISSUE TITLE
[Windows] ウィンドウを閉じるまでに時間がかかる

### ISSUE THREAD

**Issue by Npepperlinux** [shiosyakeyakini-info/miria#655]
Miriaを適当な時間使用後、ウィンドウ右上の「×」ボタンか"Alt"+"F4"キーでウィンドウを閉じる操作をしたとき、ウィンドウの描画が停止後、少ししてから閉じるようになっている。
Surface Pro6で10秒程度使用後、閉じる操作をしたところ、ウィンドウが閉じるまでに8秒かかっている。

※しばらくすればアプリが終了できる（フリーズしたままではない）ため今すぐに問題となる訳ではない。

Miria v2.0.0+114

**Comment by 4ster1sk** [comment]
window_managerを0.4.3に更新してみたものの変化なし
