### ISSUE TITLE
[Linux]起動時ウィンドウ位置の復元ができていない

### ISSUE THREAD

**Issue by 4ster1sk** [shiosyakeyakini-info/miria#674]

**Comment by Npepperlinux** [comment]
GNOME Waylandセッションでは保存されない（読み取らない？）けどGNOME X11セッションでは問題なく機能してる模様

**Comment by 4ster1sk** [comment]
KDE Plasma 5.27.5(Wayland)だと起きるので、Wayland特有…？

**Comment by Npepperlinux** [comment]
ウィンドウの位置操作をアプリ側で行うのが非推奨で、実際にWayland環境では利用できないようになっている…ということだろうか
https://discourse.gnome.org/t/how-to-center-gtkwindows-in-gtk4/3112 （画面中央に配置するAPIがGTK4で無くなったことについての質問）

**Comment by 4ster1sk** [comment]
現状の仕様な感じっぽい。
waylandでどうしてもウィンドウを移動する必要があるなら`GDK_BACKEND=x11`でXWaylandを使うしかなさそう。
